# Generated by Django 5.2.7 on 2025-12-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RESERVA', 'Reserva'), ('RETIRADA', 'Retirada'), ('DEVOLUCAO', 'Devolução')], max_length=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armamentos.armamento')),
            ],
        ),
    ]
