# Generated by Django 5.2.7 on 2025-12-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='responsavel',
            field=models.CharField(default='Sistema', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('SAIDA', 'Cautela (Saída)'), ('ENTRADA', 'Devolução (Entrada)')], default='SAIDA', max_length=10),
            preserve_default=False,
        ),
    ]
