# Generated by Django 5.2.7 on 2025-12-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
